import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/util/views/banner";
import { Container, Row, Col } from "react-bootstrap";
import { dev_phase } from "../next.config";
import { fechMe } from "../state_management/slices/user-slices/userSlice";
import axios from "axios";
import VideoCard from "../components/util/videos/videoCard";
import { getAllVideos } from "../helper/videoFetchig";

//==========================================================
export default function Home(props) {
  //----------initional data and states----------
  const { videos } = props.loadedVideos;

  if (!videos) {
    return <>loading</>;
  }

  return (
    <>
      <Head>
        <title>Orange Tube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid>
        <Row className="pt-2 justify-content-center ">
          {videos.map((video, index) => (
            <VideoCard
              writer={video.writer.userName}
              userImage={video.writer.avatarPath}
              title={video.title}
              description={video.description}
              thumbnail={video.thumbnail}
              duration={video.duration}
              videoId={video._id}
            />
          ))}

          <footer className={styles.footer}></footer>
        </Row>
      </Container>
    </>
  );
}

//=======================server side=======================

export async function getStaticProps() {
  const videos = await getAllVideos();
  return {
    props: { loadedVideos: videos },
    revalidate: 2,
  };
}
