import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/util/views/banner";
import { Container, Row, Col } from "react-bootstrap";
//==========================================================
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Orange Tube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
          <Col>
            {" "}
            <h1>home page</h1>
            <main className={styles.main}></main>{" "}
            <footer className={styles.footer}></footer>
          </Col>
        </Row>
      </Container>
    </div>
  );
}
